swagger: '2.0'
info:
  title: 'PDF Manipulation API'
  description: 'API for manipulating PDF files'
  version: '1.0'
paths:
  /delete_pages:
    post:
      tags:
        - 'PDF Manipulation'
      description: 'Delete specific pages from a PDF file'
      consumes:
        - 'multipart/form-data'
      parameters:
        - name: 'pdf_file_tobedeleted'
          in: 'formData'
          type: 'file'
          required: true
          description: 'PDF file to be processed'
        - name: 'pages_to_delete'
          in: 'formData'
          type: 'array'
          items:
            type: 'integer'
          required: true
          description: 'List of page numbers to delete'
      responses:
        '200':
          description: 'PDF pages deleted successfully'

  /merge_pdfs:
    post:
      tags:
        - 'PDF Manipulation'
      description: 'Merge multiple PDF files into one'
      consumes:
        - 'multipart/form-data'
      parameters:
        - name: 'pdf_files'
          in: 'formData'
          type: 'file'
          required: true
          description: 'List of PDF files to be merged'
      responses:
        '200':
          description: 'PDF files merged successfully'
