swagger: '2.0'
info:
  title: My API
  description: Example API using Flask and Flasgger
  version: '1.0'
paths:
  /:
    get:
      tags:
        - Root
      summary: Root endpoint
      description: Returns a JSON response with a "text" key.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Response'
    post:
      tags:
        - Root
      summary: Root endpoint
      description: Returns a JSON response with a "text" key.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Response'
definitions:
  Response:
    type: object
    properties:
      text:
        type: string
